-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 20:53:23 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`edital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edital` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modalidade` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `edital_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modalidade_edital1_idx` (`edital_id` ASC) VISIBLE,
  CONSTRAINT `fk_modalidade_edital1`
    FOREIGN KEY (`edital_id`)
    REFERENCES `mydb`.`edital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaga` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `modalidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaga_modalidade1_idx` (`modalidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_vaga_modalidade1`
    FOREIGN KEY (`modalidade_id`)
    REFERENCES `mydb`.`modalidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscricao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `vaga_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inscricao_vaga1_idx` (`vaga_id` ASC) VISIBLE,
  CONSTRAINT `fk_inscricao_vaga1`
    FOREIGN KEY (`vaga_id`)
    REFERENCES `mydb`.`vaga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupo_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subgrupo` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subgrupo_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_subgrupo_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `mydb`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anexo` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `edital_id` INT NOT NULL,
  `inscricao_id` INT NULL,
  `categoria_id` INT NOT NULL,
  `subgrupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anexo_edital_idx` (`edital_id` ASC) VISIBLE,
  INDEX `fk_anexo_inscricao1_idx` (`inscricao_id` ASC) VISIBLE,
  INDEX `fk_anexo_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_anexo_subgrupo1_idx` (`subgrupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_anexo_edital`
    FOREIGN KEY (`edital_id`)
    REFERENCES `mydb`.`edital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anexo_inscricao1`
    FOREIGN KEY (`inscricao_id`)
    REFERENCES `mydb`.`inscricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anexo_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anexo_subgrupo1`
    FOREIGN KEY (`subgrupo_id`)
    REFERENCES `mydb`.`subgrupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `anexo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documento_anexo1_idx` (`anexo_id` ASC) VISIBLE,
  CONSTRAINT `fk_documento_anexo1`
    FOREIGN KEY (`anexo_id`)
    REFERENCES `mydb`.`anexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sync_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sync_log` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `iniciado` DATETIME NULL,
  `edital_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sync_log_edital1_idx` (`edital_id` ASC) VISIBLE,
  INDEX `fk_sync_log_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_sync_log_edital1`
    FOREIGN KEY (`edital_id`)
    REFERENCES `mydb`.`edital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sync_log_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
